language: java
jdk:
  - oraclejdk8

# command to run tests
script: sh -c 'mkdir -p wilayah-indonesia/resources &&  cp -r data/list_of_area wilayah-indonesia/resources && cd wilayah-indonesia && mvn test'